# Generated by Django 2.2.17 on 2021-01-07 22:18

from django.db import migrations
import django_resized.forms
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_auto_20201229_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='PNG', keep_meta=True, quality=0, size=[80, 80], upload_to=job.models.image_upload),
        ),
    ]
